---
title: De positie van een element fixeren
hero_image: images/banner.png
description: De positie van een element fixeren
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: De positie van een element fixeren
