title: Fix the position of an element
hero_image: images/banner.png
description: Fix the position of an element
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Fix the position of an element
