title: Fixer la position d'un élément
hero_image: images/banner.png
description: Fixe la position d'un élément
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Fixer la position d'un élément
